server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  port: 20008

eureka:
  client:
    service-url:
      defaultZone: http://admin:14780118635@118.24.38.46:10001/eureka/
  instance:
    prefer-ip-address: true

ribbon:                       #ribbon配置（Feign的实现基于Ribbon，因此此配置也适用）
  eager-load:
    enabled: true             #开启饥饿加载模式 让RibbonClient提前加载，而非第一次调用时加载

spring:
  application:
    name: ssaw-authenticate-center
  rabbitmq:
    host: 118.24.38.46
    port: 5672
    username: husen
    password: 521428
    virtual-host: /
  zipkin:
    sender:
      type: rabbit

  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

  datasource:
    url: jdbc:mysql://118.24.38.46:3306/ssaw_authenticate_center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 521428Slyt!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: mergeStat,config,slf4j
      max-active: 10000
      initial-size: 2
      max-wait: 60000
      min-idle: 3
      time-between-eviction-runs-millis: 18000000
      min-evictable-idle-time-millis: 1000000
      validation-query: SELECT1FROMDUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 100
      max-pool-prepared-statement-per-connection-size: 50
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: false
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect

  redis:
    host: 118.24.38.46
    port: 6379
    password: 521428Slyt
    database: 14

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000
  header:
    bearer-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiU1NBVy1VU0VSLVJFU09VUkNFIl0sInVzZXJfbmFtZSI6ImFkbWluIiwic2NvcGUiOlsiVVNFUl9XUklURSIsIlVTRVJfUk9MRV9XUklURSIsIlVTRVJfUkVBRCIsIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiZXhwIjoxNTQ2Njc3MTczLCJhdXRob3JpdGllcyI6WyJVU0VSIl0sImp0aSI6IjYzY2RjNzZlLWUxYTQtNDQ3My1iODgxLWU3MGExM2MyMmUwOSIsImNsaWVudF9pZCI6IlN0YXRpc3RpY2FsQ2VydGlmaWNhdGlvbkNlbnRlciJ9.ee3LoIOgH1YGBRJWQrrycYkRQlTS0u2xi4-8kjl7nu3XxBvRafeG432DLyj-smR5GjbS5YYXwPV4V0z_CkTqJD3dBqvXRBJ28TDR79igzzrGUQg7-vYElD0MM3aWv_LINLwofjBPGKlI8etnkVrfp5cHzFqdn11gCowGtoN67Uj9QQA_2Smih6bSMwh58VwrwP0TpIQPmjDDsuTVdDSL_782Btb_X1BmT-XXGpacFxwXTsAtxsCW0wyS7nIm4Qo6qWgAAYn33ZhQ8ISAnNZisOy94uo1AYfcJ2tp-iFtrr8sBQibvDPC9wAbHR4PixMfNesg4BgRYnVYntzl3GalWQ
inner:
  security:
    config:
      app1:
        clientId: 233
      app2:
        clientId: 244