server:
  port: 9999

spring:
  application:
    name: SMS-CENTER
  security:
    user:
      name: admin
      password: 123456

ssaw:
  rocketmq:
    namesrv-addr: 172.18.0.2:9876;172.18.0.3:9876
    group-name: ssaw-sms-center
    instance-name: ${spring.application.name}
    queue-nums: 8