server:
  port: 20007
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  servlet:
    session:
      cookie:
        name: UISESSION
  max-http-header-size: 4048576

spring:
  application:
    name: ssaw-ui
  security:
    user:
      password: admin
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 118.24.38.46
    port: 5672
    username: husen
    password: 521428
    virtual-host: /
  cloud:
    stream:
      bindings:
        uploadToOutput:
          destination: remoteEvent
          group: event

security:
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: pig
      client-secret: 521428Slyt
      access-token-uri: http://localhost:20006/oauth/token
      user-authorization-uri: http://localhost:20006/oauth/authorize
      auto-approve-scopes: ALL
    resource:
      user-info-uri: http://localhost:20006/user
      prefer-token-info: false

eureka:
  client:
    service-url:
      defaultZone: http://admin:14780118635@118.24.38.46:10001/eureka/
  instance:
    prefer-ip-address: true   #注册服务时使用ip而非计算机名

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


