server:
  port: 22222

spring:
  application:
    name: zedemo
  datasource:
    url: jdbc:mysql://10.13.29.145:3306/oms?useUnicode=true&characterEncoding=utf-8
    username: omsdev
    password: Cd1919#omsdev
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  main:
    allow-bean-definition-overriding: true