server:
  port: 16002


eureka:
  client:
    service-url:
      defaultZone: http://admin:14780118635@localhost:10001/eureka/
  instance:
    prefer-ip-address: true #注册服务时使用ip而非计算机名

spring:
  application:
    name: ssaw-turbine-stream

  rabbitmq:                 #rabbit配置
    host: localhost
    port: 5672
    username: husen
    password: 521428
    virtual-host: /
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${spring.rabbitmq.host}
                port: ${spring.rabbitmq.port}
                username: ${spring.rabbitmq.username}
                password: ${spring.rabbitmq.password}
                virtual-host: ${spring.rabbitmq.virtual-host}
      default-binder: rabbit
#hystrix:
#  stream:
#    queue:
#      destination: ${system.message.turbine}
#management:
#  endpoint:
#    hystrix:
#      stream:
#        enabled: false
#turbine:
#  stream:
#    destination: ${system.message.turbine}







